export default {
  seniorFilter: 'Senior Filter',
  clearAll: 'clear all',
  addCondition: 'add condition',
  aboveCondition: 'above condition',
  anyOne: 'Any One',
  all: 'All',
  query: 'query',
  exactDate: 'exact date',
  dateRange: 'date range',
  today: 'today',
  tomorrow: 'tomorrow',
  yesterday: 'yesterday',
  thisWeek: 'this week',
  lastWeek: 'last week',
  thisMonth: 'this month',
  lastMonth: 'last month',
  withinThePastSevenDays: 'within the past seven days',
  withinThePastThirtyDays: 'Within the past thirty days',
  equal: 'equal',
  before: 'before',
  after: 'after',
  empty: 'empty',
  nonEmpty: 'non empty',
  batchOperation: 'batch operation',
  customDescription: 'custom description',
  cancel: 'cancel',
  confirm: 'confirm',
  filter: 'filter',
  reset: 'reset',
  sort: 'sort',
  ascendingOrder: 'ascending order',
  descendingOrder: 'descending order',
  clearSorting: 'clear sorting',
  hide: 'hide',
  retract: 'retract',
  uploadDragSign: 'Click or drag the file here to upload',
  uploadFile: 'upload file',
  selectFile: 'select file',
  remove: 'remove',
  view: 'view',
  customView: 'custom view',
  input: 'Please Input',
  success: 'success',
  error: 'error',
  warning: 'warning',
  noData: 'no data',
  selectedFields: 'Selected',
  unselectedFields: 'Unselected',
  restoreDefault: 'Restore',
  searchHeaderName: 'Search Header Name',
  showLunar: 'show lunar',
  next: 'next',
  previous: 'previous',
  finish: 'finish',
  searchTable: 'search table data',
  total: 'total',
  data: 'data',
  showAll: 'show all',
  gt: 'gt',
  lt: 'lt',
  gte: 'gte',
  lte: 'lte',
  contain: 'contain',
  notEqual: 'not eaual',
  clearData: 'Clear Data',
  enterInputSearch: 'Press Enter to search',
  within7days: 'within 7 days',
  within15days: 'within 15 days',
  curMonth: 'current month',
  curQuarter: 'current quarter',
  curYear: 'current year'
};