declare module 'vue' {
  // GlobalComponents for Volar
  export interface GlobalComponents {
    KBadge: typeof import('@ksware/ksw-ux')['KBadge']
    KButton: typeof import('@ksware/ksw-ux')['KButton']
    KButtonContainer: typeof import('@ksware/ksw-ux')['KButtonContainer']
    KCalendar: typeof import('@ksware/ksw-ux')['KCalendar']
    KCascader: typeof import('@ksware/ksw-ux')['KCascader']
    KCheckbox: typeof import('@ksware/ksw-ux')['KCheckbox']
    KCheckboxGroup: typeof import('@ksware/ksw-ux')['KCheckboxGroup']
    KCollapse: typeof import('@ksware/ksw-ux')['KCollapse']
    KDatePicker: typeof import('@ksware/ksw-ux')['KDatePicker']
    KDialog: typeof import('@ksware/ksw-ux')['KDialog']
    KDrawer: typeof import('@ksware/ksw-ux')['KDrawer']
    KDropdown: typeof import('@ksware/ksw-ux')['KDropdown']
    KEmpty: typeof import('@ksware/ksw-ux')['KEmpty']
    KFilter: typeof import('@ksware/ksw-ux')['KFilter']
    KFilterForm: typeof import('@ksware/ksw-ux')['KFilterForm']
    KForm: typeof import('@ksware/ksw-ux')['KForm']
    KFormItem: typeof import('@ksware/ksw-ux')['KFormItem']
    KInput: typeof import('@ksware/ksw-ux')['KInput']
    KInputNumber: typeof import('@ksware/ksw-ux')['KInputNumber']
    KOperate: typeof import('@ksware/ksw-ux')['KOperate']
    KOption: typeof import('@ksware/ksw-ux')['KOption']
    KPagination: typeof import('@ksware/ksw-ux')['KPagination']
    KPopover: typeof import('@ksware/ksw-ux')['KPopover']
    KPopconfirm: typeof import('@ksware/ksw-ux')['KPopconfirm']
    KRadio: typeof import('@ksware/ksw-ux')['KRadio']
    KRadioGroup: typeof import('@ksware/ksw-ux')['KRadioGroup']
    KSelect: typeof import('@ksware/ksw-ux')['KSelect']
    KSliderButton: typeof import('@ksware/ksw-ux')['KSliderButton']
    KSteps: typeof import('@ksware/ksw-ux')['KSteps']
    KStep: typeof import('@ksware/ksw-ux')['KStep']
    KSwitch: typeof import('@ksware/ksw-ux')['KSwitch']
    KTabs: typeof import('@ksware/ksw-ux')['KTabs']
    KTabPane: typeof import('@ksware/ksw-ux')['KTabPane']
    KTreeTable: typeof import('@ksware/ksw-ux')['KTreeTable']
    KTag: typeof import('@ksware/ksw-ux')['KTag']
    KTimeline: typeof import('@ksware/ksw-ux')['KTimeline']
    KTimelineItem: typeof import('@ksware/ksw-ux')['KTimelineItem']
    KTooltip: typeof import('@ksware/ksw-ux')['KTooltip']
    KTransfer: typeof import('@ksware/ksw-ux')['KTransfer']
    KTree: typeof import('@ksware/ksw-ux')['KTree']
    KTreeSelect: typeof import('@ksware/ksw-ux')['KTreeSelect']
    KTreeTransfer: typeof import('@ksware/ksw-ux')['KTreeTransfer']
    KUpload: typeof import('@ksware/ksw-ux')['KUpload']
    KView: typeof import('@ksware/ksw-ux')['KView']
    GFPageDetails: typeof import('@ksware/ksw-ux')['GFPageDetails']
    KDetails: typeof import('@ksware/ksw-ux')['KDetails']
    KDetailsItem: typeof import('@ksware/ksw-ux')['KDetailsItem']
    KMenuView: typeof import('@ksware/ksw-ux')['KMenuView']
    KPageDetails: typeof import('@ksware/ksw-ux')['KPageDetails']
    KPageViewBus: typeof import('@ksware/ksw-ux')['KPageViewBus']
    KPageTableView: typeof import('@ksware/ksw-ux')['KPageTableView']
    KIconPopover: typeof import('@ksware/ksw-ux')['KIconPopover']
    KPageViewBus: typeof import('@ksware/ksw-ux')['KPageViewBus']
    KPageDetails: typeof import('@ksware/ksw-ux')['KPageDetails']
    KPageTableView: typeof import('@ksware/ksw-ux')['KPageTableView']
    KDetails: typeof import('@ksware/ksw-ux')['KDetails']
    KDetailsItem: typeof import('@ksware/ksw-ux')['KDetailsItem']
    KMenuView: typeof import('@ksware/ksw-ux')['KMenuView']
    GFPageDetails: typeof import('@ksware/ksw-ux')['GFPageDetails']
    KTransferView: typeof import('@ksware/ksw-ux')['KTransferView']
  }
}

export {};
