import {
  ElAffix as KAffix,
  ElAlert as KAlert,
  ElAnchor as KAnchor,
  ElAnchorLink as KAnchorLink,
  ElAside as KAside,
  ElAutocomplete as KAutocomplete,
  ElAutoResizer as KAutoResizer,
  ElAvatar as KAvatar,
  ElBacktop as KBacktop,
  ElBreadcrumb as KBreadcrumb,
  ElBreadcrumbItem as KBreadcrumbItem,
  ElButtonGroup as KButtonGroup,
  ElCard as KCard,
  ElCarousel as KCarousel,
  ElCarouselItem as KCarouselItem,
  ElCascaderPanel as KCascaderPanel,
  ElCheckTag as KCheckTag,
  ElCol as KCol,
  ElCollapseTransition as KCollapseTransition,
  ElCollection as KCollection,
  ElCollectionItem as KCollectionItem,
  ElColorPicker as KColorPicker,
  ElConfigProvider as KConfigProvider,
  ElContainer as KContainer,
  ElCountdown as KCountdown,
  ElDescriptions as KDescriptions,
  ElDescriptionsItem as KDescriptionsItem,
  ElDivider as KDivider,
  ElDropdownMenu as KDropdownMenu,
  ElFooter as KFooter,
  ElHeader as KHeader,
  ElIcon as KIcon,
  ElImage as KImage,
  ElImageViewer as KImageViewer,
  ElInfiniteScroll as KInfiniteScroll,
  ElLink as KLink,
  ElLoading as KLoading,
  ElLoadingDirective as KLoadingDirective,
  ElLoadingService as KLoadingService,
  ElMain as KMain,
  ElMention as KMention,
  ElMenu as KMenu,
  ElMenuItem as KMenuItem,
  ElMenuItemGroup as KMenuItemGroup,
  ElNotification as KNotification,
  ElOverlay as KOverlay,
  ElPageHeader as KPageHeader,
  ElPopoverDirective as KPopoverDirective,
  ElPopper as KPopper,
  ElPopperArrow as KPopperArrow,
  ElPopperContent as KPopperContent,
  ElPopperTrigger as KPopperTrigger,
  ElProgress as KProgress,
  ElRate as KRate,
  ElRow as KRow,
  ElScrollbar as KScrollbar,
  ElSelectV2 as KSelectV2,
  ElSkeleton as KSkeleton,
  ElSkeletonItem as KSkeletonItem,
  ElSlider as KSlider,
  ElSpace as KSpace,
  ElStatistic as KStatistic,
  ElSubMenu as KSubMenu,
  ElText as KText,
  ElTimeSelect as KTimeSelect,
  ElTimePicker as KTimePicker,
  ElTour as KTour,
  ElTourStep as KTourStep,
  ElWatermark as KWatermark,
  ElRadioButton as KRadioButton,
  ElCheckboxButton as KCheckboxButton
} from 'element-plus';

export {
  KAffix,
  KAlert,
  KAnchor,
  KAnchorLink,
  KAside,
  KAutocomplete,
  KAutoResizer,
  KAvatar,
  KBacktop,
  KBreadcrumb,
  KBreadcrumbItem,
  KButtonGroup,
  KCard,
  KCarousel,
  KCarouselItem,
  KCascaderPanel,
  KCheckTag,
  KCol,
  KCollapseTransition,
  KCollection,
  KCollectionItem,
  KColorPicker,
  KConfigProvider,
  KContainer,
  KCountdown,
  KDescriptions,
  KDescriptionsItem,
  KDivider,
  KDropdownMenu,
  KFooter,
  KHeader,
  KIcon,
  KImage,
  KImageViewer,
  KInfiniteScroll,
  KLink,
  KLoading,
  KLoadingDirective,
  KLoadingService,
  KMain,
  KMention,
  KMenu,
  KMenuItem,
  KMenuItemGroup,
  KNotification,
  KOverlay,
  KPageHeader,
  KPopoverDirective,
  KPopper,
  KPopperArrow,
  KPopperContent,
  KPopperTrigger,
  KProgress,
  KRate,
  KRow,
  KScrollbar,
  KSelectV2,
  KSkeleton,
  KSkeletonItem,
  KSlider,
  KSpace,
  KStatistic,
  KSubMenu,
  KText,
  KTimeSelect,
  KTimePicker,
  KTour,
  KTourStep,
  KWatermark,
  KRadioButton,
  KCheckboxButton
};
