// 此文件为组件库长期维护文件，用于暴露Element-Plus组件的一些方法给外部调用
// Element-plus更新后需要同步更新此文件
const elExposeMethods = {
  KButton: ['ref', 'size', 'type', 'disabled', 'shouldAddSpace'],
  KCascader: ['getCheckedNodes', 'cascaderPanelRef', 'togglePopperVisible', 'contentRef'],
  KInput: ['blur',
    'focus',
    'clear',
    'input',
    'ref',
    'resizeTextarea',
    'select',
    'textarea',
    'textareaStyle',
    'isComposing'],
  KInputNumber: ['blur', 'focus'],
  KSwitch: ['focus'],
  KSelect: ['blur', 'focus'],
  KDatePicker: ['focus', 'handleOpen', 'handleClose'],
  KUpload: ['abort', 'submit', 'clearFiles', 'handleStart', 'handleRemove'],
  KTransfer: ['clearQuery'],
  KPopover: ['popperRef', 'hide'],
  KDialog: ['resetPostion'],
  KTooltip: ['popperRef',
    'contentRef',
    'isFocusInsideContent',
    'onOpen',
    'onClose',
    'updatePopper',
    'hide'],
  KDrawer: ['handleClose'],
  KForm: ['validate', 'validateField', 'resetFields', 'scrollToField', 'clearValidate', 'fields'],
  KFormItem: ['size',
    'validateMessage',
    'validateState',
    'validate',
    'resetField',
    'clearValidate'],
  KTree: ['filter',
    'getCheckedNodes',
    'getCheckedKeys',
    'setCheckedKeys',
    'setChecked',
    'setExpandedKeys',
    'getHalfCheckedNodes',
    'getHalfCheckedKeys',
    'getCurrentKey',
    'getCurrentNode',
    'setCurrentKey',
    'getNode',
    'expandNode',
    'collapseNode',
    'setData',
    'scrollTo',
    'scrollToNode'],
  KDropdown: ['handleOpen', 'handleClose'],
  KTreeSelect: ['blur',
    'focus',
    'filter',
    'updateKeyChildren',
    'getCheckedNodes',
    'setCheckedNodes',
    'getCheckedKeys',
    'setCheckedKeys',
    'setChecked',
    'getHalfCheckedNodes',
    'getHalfCheckedKeys',
    'getCurrentKey',
    'getCurrentNode',
    'setCurrentKey',
    'setCurrentNode',
    'getNode',
    'remove',
    'append',
    'insertBefore',
    'insertAfter']
};

export default elExposeMethods;