name: "Generate changelog"

on:
  workflow_dispatch:
  push:
    branches:
      - dev
    paths:
      - 'cliff.toml'
      - '.github/workflows/git-cliff-changelog-generator.yml'
    tags:
      - "v*"
    workflow_dispatch:

permissions:
  id-token: "write"
  contents: "write"
  packages: "write"
  pull-requests: "read"

jobs:
  changelog:
    name: Generate changelog
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get dependencies versions from package.json
        id: get-versions
        run: |
          VXE_TABLE_VERSION=$(jq -r '.peerDependencies["vxe-table"]' package.json | sed 's/^\^//')
          ELEMENT_PLUS_VERSION=$(jq -r '.peerDependencies["element-plus"]' package.json | sed 's/^\^//')
          echo "VXE_TABLE_VERSION=$VXE_TABLE_VERSION" >> $GITHUB_ENV
          echo "ELEMENT_PLUS_VERSION=$ELEMENT_PLUS_VERSION" >> $GITHUB_ENV

      - name: Update cliff.toml with versions
        run: |
          sed -i "s/{{ vxe_table_version }}/$VXE_TABLE_VERSION/g" cliff.toml
          sed -i "s/{{ element_plus_version }}/$ELEMENT_PLUS_VERSION/g" cliff.toml

      - name: Generate latest changelog
        uses: orhun/git-cliff-action@v4
        id: latest-changelog
        with:
          config: cliff.toml
          args: --verbose --latest --strip header
        env:
          OUTPUT: LATEST_CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Insert latest changelog after header
        run: |
          awk '/^# Changelog/{print; getline; print; print ""; system("cat LATEST_CHANGELOG.md"); next}1' CHANGELOG.md > TEMP_CHANGELOG.md
          mv TEMP_CHANGELOG.md CHANGELOG.md

      - name: Copy CHANGELOG.md to docs directory
        run: |
          mkdir -p docs/docs
          cp CHANGELOG.md docs/docs/CHANGELOG.md

      - name: Commit full changelog
        run: |
          git checkout dev
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add CHANGELOG.md
          git add docs/docs/CHANGELOG.md
          git commit -m "Update changelog and copy to docs directory" || echo "No changes to commit"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git dev

      # 触发部署工作流
      - name: Trigger Deploy Docs
        uses: peter-evans/repository-dispatch@v3
        with:
          event-type: trigger-deploy
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'

      # 发送企业微信通知
      # - name: WeChat Work notification
      #   if: steps.latest-changelog.outputs.content != ''
      #   uses: chf007/action-wechat-work@master
      #   env:
      #     WECHAT_WORK_BOT_WEBHOOK: ${{secrets.WECHAT_WORK_BOT_WEBHOOK}}
      #   with:
      #     msgtype: markdown
      #     content: "${{ steps.latest-changelog.outputs.content }}"