name: "Generate changelog"

on:
  workflow_dispatch:
  push:
    branches:
      - dev
    paths:
      - 'cliff.toml'
      - '.github/workflows/git-cliff-changelog-generator.yml'
    tags:
      - "v*"

permissions:
  id-token: "write"
  contents: "write"
  packages: "write"
  pull-requests: "read"

jobs:
  changelog:
    name: Generate changelog
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # 生成的 Changelog 上下文
      - name: Generate full changelog
        uses: orhun/git-cliff-action@v4
        with:
          config: cliff.toml
          args: --context
        env:
          OUTPUT: context.json
          GITHUB_REPO: ${{ github.repository }}

      - name: Generate dependency changes and inject
        run: |
          node dependenciesChange/generate_deps.js && node dependenciesChange/inject_deps.js

      # 根据上下文生成完整的 Changelog
      - name: Generate full changelog
        uses: orhun/git-cliff-action@v4
        with:
          config: cliff.toml
          args: --verbose --from-context context.json
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}

      # 生成最新版本的 Changelog
      - name: Generate latest changelog
        uses: orhun/git-cliff-action@v4
        id: latest-changelog
        with:
          config: cliff.toml
          args: --verbose --latest --strip header
        env:
          OUTPUT: LATEST_CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}

      # 将 CHANGELOG.md 复制到 docs/docs/CHANGELOG.md
      - name: Copy CHANGELOG.md to docs directory
        run: |
          mkdir -p docs/docs
          cp CHANGELOG.md docs/docs/CHANGELOG.md

      # 提交完整的 Changelog 和复制的文件
      - name: Commit full changelog
        run: |
          git checkout dev
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          set +e
          git add dependenciesVersion.json
          git add CHANGELOG.md
          git add docs/docs/CHANGELOG.md
          git commit -m "Update changelog and copy to docs directory"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git dev

      # 触发部署工作流
      - name: Trigger Deploy Docs
        uses: peter-evans/repository-dispatch@v3
        with:
          # token: ${{ secrets.PAT }}
          event-type: trigger-deploy
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'

      # 发送企业微信通知
      - name: WeChat Work notification
        if: steps.latest-changelog.outputs.content != ''
        uses: chf007/action-wechat-work@master
        env:
          WECHAT_WORK_BOT_WEBHOOK: ${{secrets.WECHAT_WORK_BOT_WEBHOOK}}
        with:
          msgtype: markdown
          content: "${{ steps.latest-changelog.outputs.content }}"